### ISSUE TITLE
Stuttering gameplay & error messages

### ISSUE THREAD

**Issue by Taraxkrot** [StarCoreSE/InvalidsMiscMods#26]
**_Problem_**: Shipyard mod seems to cause dedicated server stuttering (game freezes ->un-freezes in rapid succession: Rince & repeat). 

**_Background_**: I am hosting a dedicated server for me and my friends (Vanilla dedicated server). The game at random times starts stuttering until a restart. Seemingly even when the blocks are turned off. The server log gets spammed with the following messages.

> SpaceEngineersDedicated_X_x.txt
> 
> 2024-07-02 17:35:12.093 - Thread:  16 ->  #⁠sHIPYARD MOD: THREAD EXCEPTION, CHECK MOD LOG FOR MORE INFO.
> 2024-07-02 17:35:12.316 - Thread:  16 ->  #⁠sHIPYARD MOD: EXCEPTION: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: index
>    at System.Linq.Enumerable.ElementAt[TSource](IEnumerable1 source, Int32 index)
>    at ShipyardMod.ProcessHandlers.ProcessConveyorCache.Handle()
>    at ShipyardMod.ShipyardCore.<RunProcessHandlers>b__18_0()
>    at ParallelTasks.DelegateWork.DoWork(WorkData workData)
>    at ParallelTasks.WorkItem.DoWork(Int32 expectedID)
> 2024-07-02 17:35:12.351 - Thread:   7 ->  Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: index
>    at System.Linq.Enumerable.ElementAt[TSource](IEnumerable1 source, Int32 index)
>    at ShipyardMod.ProcessHandlers.ProcessConveyorCache.Handle()
>    at ShipyardMod.ShipyardCore.<RunProcessHandlers>b__18_0()
>    at ParallelTasks.DelegateWork.DoWork(WorkData workData)
>    at ParallelTasks.WorkItem.DoWork(Int32 expectedID) 

_List of mods_: https://steamcommunity.com/sharedfiles/filedetails/?id=1458561745

In the ShipyardMod.log file the following is repeated.

_

> [21:16:01:1850] Thread Exception: ProcessConveyorCache: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: index
>    at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
>    at ShipyardMod.ProcessHandlers.ProcessConveyorCache.Handle()
>    at ShipyardMod.ShipyardCore.<RunProcessHandlers>b__18_0()

_

Save file can be downloaded here, it was to big for me to upload here: https://drive.google.com/file/d/1FWOCR52Kbvmpp1to1skIbIT4TIdZB-kF/view?usp=sharing

**Comment by InvalidArgument3** [comment]
thanks king
will look at this, best bug report i've ever seen
